[package]
name = "mybatis-sql"
version = "1.0.0"
edition = "2021"
rust-version = "1.59.0"
authors = ["James Zow <Jameszow@163.com>"]
license = "Apache-2.0 license"
description = "mybatis sql"

[dependencies]
once_cell = "1.9.0"
mybatis-core = { version = "1.0.0", path = "../mybatis-core" }
macros = { version = "1.0.0", path = "../macros" }

#serde
serde = { version = "1", features = ["derive"] }
rbson = "2.0.3"