[workspace]
members = [
    "attributes",
    "conversion",
    "customtypes",
    "expressions",
    "flowofcontrol",
    "formatprint",
    "modules",
    "types",
    "varbindings",
    "utiltest",
    "primitives",
    "function",
    "crates",
]