[package]
name = "mybatis-tests"
version = "1.0.0"
edition = "2021"
rust-version = "1.59.0"
authors = ["James Zow <Jameszow@163.com>"]
license = "Apache-2.0 license"
description = "mybatis tests"

[dependencies]
# mybatis-core = {version = "1.0.0", path = "../mybatis-core"}
mybatis-plus = {version = "1.0.0", path = "../mybatis-plus"}
mybatis-util = {version = "1.0.0", path = "../mybatis-util"}