[package]
name = "DataService"
version = "0.1.0"
authors = ["JamesZow <Jameszow@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
mysql = "20.0.0"