[package]
name = "crates_jameszow"
version = "0.1.0"
authors = ["JamesZow <Jameszow@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]