name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    if: github.repository == 'summer-mybatis/mybatis/'
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v3
      with:
        repository: summer-rust/summer-mybatis
        path: mybatis
        run: cargo build --verbose
    - name: Run tests
      uses: actions/checkout@v3
      with:
        repository: summer-rust/summer-mybatis
        path: mybatis
        run: cargo test --verbose
